# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abbreviations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', models.IntegerField()),
                ('abbr', models.CharField(max_length=16)),
                ('abbreviation', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'abbreviations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Datasources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('datasources_type', models.IntegerField()),
                ('baseurl', models.CharField(max_length=120)),
                ('targeturl', models.CharField(max_length=120)),
                ('primarylanguage', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('active', models.TextField()),
            ],
            options={
                'db_table': 'datasources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatasourcesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasource_type', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'datasources_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documentstorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, max_length=255, null=True)),
                ('datasource', models.IntegerField()),
                ('datasources_type', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(max_length=320)),
                ('title', models.TextField()),
                ('date', models.DateTimeField()),
                ('author', models.TextField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('language', models.IntegerField(blank=True, null=True)),
                ('filepath', models.CharField(max_length=320)),
            ],
            options={
                'db_table': 'documentstorage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'languages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastactivity', models.IntegerField()),
                ('databasesize', models.IntegerField()),
                ('graphdatabaselink', models.IntegerField()),
            ],
            options={
                'db_table': 'metadata',
                'managed': False,
            },
        ),
    ]
