# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentstorage',
            options={'managed': True},
        ),
    ]
