# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0002_auto_20170418_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentstorage',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='documentstorage',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='documentstorage',
            name='slug',
            field=models.CharField(default=None, max_length=320),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentstorage',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
