# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_manager', '0004_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentstorage',
            name='language',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
